{% set name = "pyquaternion" %}
{% set version = "0.9.9" %}

conda_build:
  config_file: conda_build_config.yaml

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/KieranWynn/pyquaternion.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  preserve_egg_dir: True

requirements:
  build:
    - python

  run:
    - python >=3.9
    - numpy

test:
  imports:
    - pyquaternion

about:
  home: "https://kieranwynn.github.io/pyquaternion"
  license: "MIT License (MIT)"
  license_family: MIT
  summary: "A fully featured, pythonic library for representing and using quaternions."

extra:
  recipe-maintainers:
    - krande
